.TH "RANDOMART" "1" "August 2017" "" ""
.SH "NAME"
\fBrandomart\fR \- Randomart Command Line Interface
.SH SYNOPSIS
.P
randomart [thing]
.SH DESCRIPTION
.P
\fBrandomart\fP is a command line tool that will display an ascii representation
of the thing that is passed into it\. Whatever that is called\.
.SH AUTHOR
.P
Jamie Young yungjmes!gmail\.com http://yungjames\.com

